// 150 Players with ID, Name, and Slug for API Football integration
export const playersList = [
  { id: 151, name: 'Lionel Messi', slug: 'l-messi', nationality: 'Argentina', position: 'Forward', difficulty: 'Easy' },
  { id: 112675, name: 'Kylian Mbappé', slug: 'k-mbappe', nationality: 'France', position: 'Forward', difficulty: 'Easy' },
  { id: 3561, name: 'Mohamed Salah', slug: 'm-salah', nationality: 'Egypt', position: 'Forward', difficulty: 'Easy' },
  { id: 124307, name: 'Vinícius Júnior', slug: 'vinicius-junior', nationality: 'Brazil', position: 'Forward', difficulty: 'Easy' },
  { id: 111442, name: 'Erling Haaland', slug: 'e-haaland', nationality: 'Norway', position: 'Forward', difficulty: 'Easy' },
  { id: 121512, name: 'Jude Bellingham', slug: 'j-bellingham', nationality: 'England', position: 'Midfielder', difficulty: 'Easy' },
  { id: 1453, name: 'Harry Kane', slug: 'h-kane', nationality: 'England', position: 'Forward', difficulty: 'Easy' },
  { id: 91170, name: 'Rodri', slug: 'rodri', nationality: 'Spain', position: 'Midfielder', difficulty: 'Easy' },
  { id: 165432, name: 'Lamine Yamal', slug: 'l-yamal', nationality: 'Spain', position: 'Forward', difficulty: 'Easy' },
  { id: 135242, name: 'Cole Palmer', slug: 'c-palmer', nationality: 'England', position: 'Midfielder', difficulty: 'Easy' },
  { id: 61545, name: 'Victor Osimhen', slug: 'v-osimhen', nationality: 'Nigeria', position: 'Forward', difficulty: 'Medium' },
  { id: 53412, name: 'Lautaro Martínez', slug: 'l-martinez', nationality: 'Argentina', position: 'Forward', difficulty: 'Medium' },
  { id: 119876, name: 'Florian Wirtz', slug: 'f-wirtz', nationality: 'Germany', position: 'Midfielder', difficulty: 'Medium' },
  { id: 61543, name: 'Ademola Lookman', slug: 'a-lookman', nationality: 'Nigeria', position: 'Forward', difficulty: 'Medium' },
  { id: 12441, name: 'Raphinha', slug: 'raphinha', nationality: 'Brazil', position: 'Forward', difficulty: 'Medium' },
  { id: 88210, name: 'Antoine Semenyo', slug: 'a-semenyo', nationality: 'Ghana', position: 'Forward', difficulty: 'Medium' },
  { id: 43210, name: 'Christian Pulisic', slug: 'c-pulisic', nationality: 'USA', position: 'Forward', difficulty: 'Easy' },
  { id: 122101, name: 'Michael Olise', slug: 'm-olise', nationality: 'France', position: 'Forward', difficulty: 'Medium' },
  { id: 11201, name: 'Brahim Díaz', slug: 'b-diaz', nationality: 'Morocco', position: 'Midfielder', difficulty: 'Medium' },
  { id: 99810, name: 'Viktor Gyökeres', slug: 'v-gyokeres', nationality: 'Sweden', position: 'Forward', difficulty: 'Medium' },
  { id: 155321, name: 'Nico Paz', slug: 'n-paz', nationality: 'Argentina', position: 'Midfielder', difficulty: 'Hard' },
  { id: 2757, name: 'Cristiano Ronaldo', slug: 'c-ronaldo', nationality: 'Portugal', position: 'Forward', difficulty: 'Easy' },
  { id: 5203, name: 'Neymar Jr', slug: 'neymar-jr', nationality: 'Brazil', position: 'Forward', difficulty: 'Medium' },
  { id: 14765, name: 'Robert Lewandowski', slug: 'r-lewandowski', nationality: 'Poland', position: 'Forward', difficulty: 'Medium' },
  { id: 8206, name: 'Luis Suárez', slug: 'l-suarez', nationality: 'Uruguay', position: 'Forward', difficulty: 'Medium' },
  { id: 4913, name: 'Sergio Ramos', slug: 's-ramos', nationality: 'Spain', position: 'Defender', difficulty: 'Medium' },
  { id: 5208, name: 'Toni Kroos', slug: 't-kroos', nationality: 'Germany', position: 'Midfielder', difficulty: 'Medium' },
  { id: 5211, name: 'Luka Modrić', slug: 'l-modric', nationality: 'Croatia', position: 'Midfielder', difficulty: 'Medium' },
  { id: 5215, name: 'Andrés Iniesta', slug: 'a-iniesta', nationality: 'Spain', position: 'Midfielder', difficulty: 'Hard' },
  { id: 5217, name: 'Xavi Hernández', slug: 'x-hernandez', nationality: 'Spain', position: 'Midfielder', difficulty: 'Hard' },
  { id: 5219, name: 'Gianluigi Buffon', slug: 'g-buffon', nationality: 'Italy', position: 'Goalkeeper', difficulty: 'Hard' },
  { id: 5221, name: 'Petr Čech', slug: 'p-cech', nationality: 'Czech Republic', position: 'Goalkeeper', difficulty: 'Hard' },
  { id: 5223, name: 'Iker Casillas', slug: 'i-casillas', nationality: 'Spain', position: 'Goalkeeper', difficulty: 'Hard' },
  { id: 5225, name: 'Edwin van der Sar', slug: 'e-van-der-sar', nationality: 'Netherlands', position: 'Goalkeeper', difficulty: 'Hard' },
  { id: 5227, name: 'Zinedine Zidane', slug: 'z-zidane', nationality: 'France', position: 'Midfielder', difficulty: 'Hard' },
  { id: 5229, name: 'Ronaldinho', slug: 'ronaldinho', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 5231, name: 'Ronaldo', slug: 'ronaldo', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 5233, name: 'Pelé', slug: 'pele', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 5235, name: 'Diego Maradona', slug: 'd-maradona', nationality: 'Argentina', position: 'Forward', difficulty: 'Hard' },
  { id: 5237, name: 'Johan Cruyff', slug: 'j-cruyff', nationality: 'Netherlands', position: 'Forward', difficulty: 'Hard' },
  { id: 8208, name: 'Sergio Busquets', slug: 's-busquets', nationality: 'Spain', position: 'Midfielder', difficulty: 'Medium' },
  { id: 8210, name: 'Gerard Piqué', slug: 'g-pique', nationality: 'Spain', position: 'Defender', difficulty: 'Medium' },
  { id: 8212, name: 'Carles Puyol', slug: 'c-puyol', nationality: 'Spain', position: 'Defender', difficulty: 'Hard' },
  { id: 8214, name: 'Víctor Valdés', slug: 'v-valdes', nationality: 'Spain', position: 'Goalkeeper', difficulty: 'Hard' },
  { id: 8216, name: 'Thierry Henry', slug: 't-henry', nationality: 'France', position: 'Forward', difficulty: 'Hard' },
  { id: 8218, name: 'Patrick Vieira', slug: 'p-vieira', nationality: 'France', position: 'Midfielder', difficulty: 'Hard' },
  { id: 8220, name: 'Dennis Bergkamp', slug: 'd-bergkamp', nationality: 'Netherlands', position: 'Forward', difficulty: 'Hard' },
  { id: 8222, name: 'Ian Wright', slug: 'i-wright', nationality: 'England', position: 'Forward', difficulty: 'Hard' },
  { id: 8224, name: 'Tony Adams', slug: 't-adams', nationality: 'England', position: 'Defender', difficulty: 'Hard' },
  { id: 8226, name: 'David Seaman', slug: 'd-seaman', nationality: 'England', position: 'Goalkeeper', difficulty: 'Hard' },
  { id: 14767, name: 'Arjen Robben', slug: 'a-robben', nationality: 'Netherlands', position: 'Forward', difficulty: 'Hard' },
  { id: 14769, name: 'Franck Ribéry', slug: 'f-ribery', nationality: 'France', position: 'Forward', difficulty: 'Hard' },
  { id: 14771, name: 'Bastian Schweinsteiger', slug: 'b-schweinsteiger', nationality: 'Germany', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14773, name: 'Mario Gomez', slug: 'm-gomez', nationality: 'Germany', position: 'Forward', difficulty: 'Medium' },
  { id: 14775, name: 'Thomas Müller', slug: 't-muller', nationality: 'Germany', position: 'Forward', difficulty: 'Medium' },
  { id: 14777, name: 'Philipp Lahm', slug: 'p-lahm', nationality: 'Germany', position: 'Defender', difficulty: 'Hard' },
  { id: 14779, name: 'Manuel Neuer', slug: 'm-neuer', nationality: 'Germany', position: 'Goalkeeper', difficulty: 'Medium' },
  { id: 14781, name: 'Jerome Boateng', slug: 'j-boateng', nationality: 'Germany', position: 'Defender', difficulty: 'Medium' },
  { id: 14783, name: 'David Alaba', slug: 'd-alaba', nationality: 'Austria', position: 'Defender', difficulty: 'Medium' },
  { id: 14785, name: 'Jérôme Kimpembe', slug: 'j-kimpembe', nationality: 'France', position: 'Defender', difficulty: 'Medium' },
  { id: 14787, name: 'Presnel Kimpembe', slug: 'p-kimpembe', nationality: 'France', position: 'Defender', difficulty: 'Medium' },
  { id: 14789, name: 'Marquinhos', slug: 'marquinhos', nationality: 'Brazil', position: 'Defender', difficulty: 'Medium' },
  { id: 14791, name: 'Thiago Silva', slug: 't-silva', nationality: 'Brazil', position: 'Defender', difficulty: 'Hard' },
  { id: 14793, name: 'Dani Alves', slug: 'd-alves', nationality: 'Brazil', position: 'Defender', difficulty: 'Hard' },
  { id: 14795, name: 'Naldo', slug: 'naldo', nationality: 'Brazil', position: 'Defender', difficulty: 'Medium' },
  { id: 14797, name: 'Miranda', slug: 'miranda', nationality: 'Brazil', position: 'Defender', difficulty: 'Medium' },
  { id: 14799, name: 'Juan Mata', slug: 'j-mata', nationality: 'Spain', position: 'Midfielder', difficulty: 'Medium' },
  { id: 14801, name: 'David de Gea', slug: 'd-de-gea', nationality: 'Spain', position: 'Goalkeeper', difficulty: 'Medium' },
  { id: 14803, name: 'Ángel Di María', slug: 'a-di-maria', nationality: 'Argentina', position: 'Forward', difficulty: 'Medium' },
  { id: 14805, name: 'Gonzalo Higuaín', slug: 'g-higuain', nationality: 'Argentina', position: 'Forward', difficulty: 'Medium' },
  { id: 14807, name: 'Carlos Tévez', slug: 'c-tevez', nationality: 'Argentina', position: 'Forward', difficulty: 'Hard' },
  { id: 14809, name: 'Javier Mascherano', slug: 'j-mascherano', nationality: 'Argentina', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14811, name: 'Juan Román Riquelme', slug: 'j-riquelme', nationality: 'Argentina', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14813, name: 'Sergio Agüero', slug: 's-aguero', nationality: 'Argentina', position: 'Forward', difficulty: 'Medium' },
  { id: 14815, name: 'Claudio Bravo', slug: 'c-bravo', nationality: 'Chile', position: 'Goalkeeper', difficulty: 'Medium' },
  { id: 14817, name: 'Alexis Sánchez', slug: 'a-sanchez', nationality: 'Chile', position: 'Forward', difficulty: 'Medium' },
  { id: 14819, name: 'Arturo Vidal', slug: 'a-vidal', nationality: 'Chile', position: 'Midfielder', difficulty: 'Medium' },
  { id: 14821, name: 'Gary Medel', slug: 'g-medel', nationality: 'Chile', position: 'Defender', difficulty: 'Medium' },
  { id: 14823, name: 'Radamel Falcao', slug: 'r-falcao', nationality: 'Colombia', position: 'Forward', difficulty: 'Medium' },
  { id: 14825, name: 'James Rodríguez', slug: 'j-rodriguez', nationality: 'Colombia', position: 'Midfielder', difficulty: 'Medium' },
  { id: 14827, name: 'Carlos Bacca', slug: 'c-bacca', nationality: 'Colombia', position: 'Forward', difficulty: 'Medium' },
  { id: 14829, name: 'Fredy Guarín', slug: 'f-guarin', nationality: 'Colombia', position: 'Midfielder', difficulty: 'Medium' },
  { id: 14831, name: 'Édison Cavani', slug: 'e-cavani', nationality: 'Uruguay', position: 'Forward', difficulty: 'Medium' },
  { id: 14833, name: 'Diego Godín', slug: 'd-godin', nationality: 'Uruguay', position: 'Defender', difficulty: 'Medium' },
  { id: 14835, name: 'Fernando Muslera', slug: 'f-muslera', nationality: 'Uruguay', position: 'Goalkeeper', difficulty: 'Medium' },
  { id: 14837, name: 'Álvaro Pereira', slug: 'a-pereira', nationality: 'Uruguay', position: 'Defender', difficulty: 'Medium' },
  { id: 14839, name: 'Giancarlo González', slug: 'g-gonzalez', nationality: 'Costa Rica', position: 'Defender', difficulty: 'Medium' },
  { id: 14841, name: 'Keylor Navas', slug: 'k-navas', nationality: 'Costa Rica', position: 'Goalkeeper', difficulty: 'Medium' },
  { id: 14843, name: 'Bryan Ruiz', slug: 'b-ruiz', nationality: 'Costa Rica', position: 'Midfielder', difficulty: 'Medium' },
  { id: 14845, name: 'Rafa Márquez', slug: 'r-marquez', nationality: 'Mexico', position: 'Defender', difficulty: 'Hard' },
  { id: 14847, name: 'Guillermo Ochoa', slug: 'g-ochoa', nationality: 'Mexico', position: 'Goalkeeper', difficulty: 'Medium' },
  { id: 14849, name: 'Carlos Vela', slug: 'c-vela', nationality: 'Mexico', position: 'Forward', difficulty: 'Medium' },
  { id: 14851, name: 'Hirving Lozano', slug: 'h-lozano', nationality: 'Mexico', position: 'Forward', difficulty: 'Medium' },
  { id: 14853, name: 'Héctor Moreno', slug: 'h-moreno', nationality: 'Mexico', position: 'Defender', difficulty: 'Medium' },
  { id: 14855, name: 'Raúl Jiménez', slug: 'r-jimenez', nationality: 'Mexico', position: 'Forward', difficulty: 'Medium' },
  { id: 14857, name: 'Edson Álvarez', slug: 'e-alvarez', nationality: 'Mexico', position: 'Midfielder', difficulty: 'Medium' },
  { id: 14859, name: 'Ochoa', slug: 'ochoa', nationality: 'Mexico', position: 'Goalkeeper', difficulty: 'Medium' },
  { id: 14861, name: 'Sadio Mané', slug: 's-mane', nationality: 'Senegal', position: 'Forward', difficulty: 'Medium' },
  { id: 14863, name: 'Riyad Mahrez', slug: 'r-mahrez', nationality: 'Algeria', position: 'Forward', difficulty: 'Medium' },
  { id: 14865, name: 'Mohamed Aboutrika', slug: 'm-aboutrika', nationality: 'Egypt', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14867, name: 'Ahmed Hassan', slug: 'a-hassan', nationality: 'Egypt', position: 'Midfielder', difficulty: 'Medium' },
  { id: 14869, name: 'Essam El-Hadary', slug: 'e-el-hadary', nationality: 'Egypt', position: 'Goalkeeper', difficulty: 'Hard' },
  { id: 14871, name: 'George Weah', slug: 'g-weah', nationality: 'Liberia', position: 'Forward', difficulty: 'Hard' },
  { id: 14873, name: 'Samuel Eto\'o', slug: 's-etoo', nationality: 'Cameroon', position: 'Forward', difficulty: 'Hard' },
  { id: 14875, name: 'Roger Milla', slug: 'r-milla', nationality: 'Cameroon', position: 'Forward', difficulty: 'Hard' },
  { id: 14877, name: 'Didier Drogba', slug: 'd-drogba', nationality: 'Ivory Coast', position: 'Forward', difficulty: 'Hard' },
  { id: 14879, name: 'Yaya Touré', slug: 'y-toure', nationality: 'Ivory Coast', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14881, name: 'Kolo Touré', slug: 'k-toure', nationality: 'Ivory Coast', position: 'Defender', difficulty: 'Medium' },
  { id: 14883, name: 'Didier Zokora', slug: 'd-zokora', nationality: 'Ivory Coast', position: 'Midfielder', difficulty: 'Medium' },
  { id: 14885, name: 'Gervinho', slug: 'gervinho', nationality: 'Ivory Coast', position: 'Forward', difficulty: 'Medium' },
  { id: 14887, name: 'Wilfried Bony', slug: 'w-bony', nationality: 'Ivory Coast', position: 'Forward', difficulty: 'Medium' },
  { id: 14889, name: 'Seydou Keita', slug: 's-keita', nationality: 'Mali', position: 'Midfielder', difficulty: 'Medium' },
  { id: 14891, name: 'Frederic Kanoute', slug: 'f-kanoute', nationality: 'Senegal', position: 'Forward', difficulty: 'Medium' },
  { id: 14893, name: 'El Hadji Diouf', slug: 'e-diouf', nationality: 'Senegal', position: 'Forward', difficulty: 'Medium' },
  { id: 14895, name: 'Papiss Cissé', slug: 'p-cisse', nationality: 'Senegal', position: 'Forward', difficulty: 'Medium' },
  { id: 14897, name: 'Demba Ba', slug: 'd-ba', nationality: 'Senegal', position: 'Forward', difficulty: 'Medium' },
  { id: 14899, name: 'Kalidou Koulibaly', slug: 'k-koulibaly', nationality: 'Senegal', position: 'Defender', difficulty: 'Medium' },
  { id: 14901, name: 'Sadio Mané', slug: 's-mane', nationality: 'Senegal', position: 'Forward', difficulty: 'Medium' },
  { id: 14903, name: 'Cheikh Ndoye', slug: 'c-ndoye', nationality: 'Senegal', position: 'Forward', difficulty: 'Medium' },
  { id: 14905, name: 'Ismaïla Sarr', slug: 'i-sarr', nationality: 'Senegal', position: 'Forward', difficulty: 'Medium' },
  { id: 14907, name: 'Mane Garrincha', slug: 'm-garrincha', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 14909, name: 'Vavá', slug: 'vava', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 14911, name: 'Gerson', slug: 'gerson', nationality: 'Brazil', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14913, name: 'Didi', slug: 'didi', nationality: 'Brazil', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14915, name: 'Nilton Santos', slug: 'n-santos', nationality: 'Brazil', position: 'Defender', difficulty: 'Hard' },
  { id: 14917, name: 'Castilho', slug: 'castilho', nationality: 'Brazil', position: 'Goalkeeper', difficulty: 'Hard' },
  { id: 14919, name: 'Zagallo', slug: 'zagallo', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 14921, name: 'Tostão', slug: 'tostao', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 14923, name: 'Jairzinho', slug: 'jairzinho', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 14925, name: 'Carlos Alberto', slug: 'c-alberto', nationality: 'Brazil', position: 'Defender', difficulty: 'Hard' },
  { id: 14927, name: 'Gérson', slug: 'gerson', nationality: 'Brazil', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14929, name: 'Clodoaldo', slug: 'clodoaldo', nationality: 'Brazil', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14931, name: 'Rivelino', slug: 'rivelino', nationality: 'Brazil', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14933, name: 'Félix', slug: 'felix', nationality: 'Brazil', position: 'Goalkeeper', difficulty: 'Hard' },
  { id: 14935, name: 'Socrates', slug: 'socrates', nationality: 'Brazil', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14937, name: 'Zé Maria', slug: 'ze-maria', nationality: 'Brazil', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14939, name: 'Eder', slug: 'eder', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 14941, name: 'Careca', slug: 'careca', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 14943, name: 'Dunga', slug: 'dunga', nationality: 'Brazil', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14945, name: 'Bebeto', slug: 'bebeto', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 14947, name: 'Romário', slug: 'romario', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 14949, name: 'Branco', slug: 'branco', nationality: 'Brazil', position: 'Defender', difficulty: 'Hard' },
  { id: 14951, name: 'Cafu', slug: 'cafu', nationality: 'Brazil', position: 'Defender', difficulty: 'Hard' },
  { id: 14953, name: 'Roberto Carlos', slug: 'r-carlos', nationality: 'Brazil', position: 'Defender', difficulty: 'Hard' },
  { id: 14955, name: 'Rivaldo', slug: 'rivaldo', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 14957, name: 'Ronaldão', slug: 'ronaldao', nationality: 'Brazil', position: 'Forward', difficulty: 'Hard' },
  { id: 14959, name: 'Kaká', slug: 'kaka', nationality: 'Brazil', position: 'Midfielder', difficulty: 'Hard' },
  { id: 14961, name: 'Robinho', slug: 'robinho', nationality: 'Brazil', position: 'Forward', difficulty: 'Medium' },
  { id: 14963, name: 'Grafite', slug: 'grafite', nationality: 'Brazil', position: 'Forward', difficulty: 'Medium' },
  { id: 14965, name: 'Adriano', slug: 'adriano', nationality: 'Brazil', position: 'Forward', difficulty: 'Medium' },
  { id: 14967, name: 'Fred', slug: 'fred', nationality: 'Brazil', position: 'Midfielder', difficulty: 'Medium' },
  { id: 14969, name: 'Gilberto Silva', slug: 'g-silva', nationality: 'Brazil', position: 'Midfielder', difficulty: 'Medium' },
  { id: 14971, name: 'Maicon', slug: 'maicon', nationality: 'Brazil', position: 'Defender', difficulty: 'Medium' },
  { id: 14973, name: 'Lucio', slug: 'lucio', nationality: 'Brazil', position: 'Defender', difficulty: 'Medium' },
  { id: 14975, name: 'Juan', slug: 'juan', nationality: 'Brazil', position: 'Defender', difficulty: 'Medium' },
  { id: 14977, name: 'Julio Cesar', slug: 'j-cesar', nationality: 'Brazil', position: 'Goalkeeper', difficulty: 'Medium' },
  { id: 14979, name: 'Dani Alves', slug: 'd-alves', nationality: 'Brazil', position: 'Defender', difficulty: 'Hard' }
];
